### ISSUE TITLE
9.0.2 patch

### ISSUE THREAD

**Issue by Jake-Shadle** [Bromeego/WoW-Cache#2]
The 9.0.1 cache was working fine, but yesterday was patch 9.0.2 and it appears a new cache is needed. :slightly_frowning_face:

**Comment by Bromeego** [comment]
Sorry, I didn't get a notification from Github regarding the issue. I will sort it out when I am back from holiday which will be mid-January.

**Comment by Bromeego** [comment]
Back from holiday now and managed to get a device up and running with WoW.
I had my kid run around Org, IF and SW for a few hours. 
This came from a Mac rather than my Linux box which is currently packed away.
Let me know if you have any issues and I can get my other PC up and running apologies for the delay!
[Commit #7](https://github.com/Bromeego/WoW-Cache/commit/1090fa40cc5abb90f40c3059c46ac95c8c4a9181)

**Comment by Jake-Shadle** [comment]
No worries, thanks!
